name: Node Setup
on:
  push:
    branches: [main]
jobs:
  setup-node:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
        
      - name: setup-node
        uses: actions/setup-node@v4

        
